gazebo_ros_control:
  pid_gains:
    joint1: { p: 5000, i: 50, d: 20, i_clamp_max: 50000, i_clamp_min: -50000 }
    joint2: { p: 5000, i: 50, d: 20, i_clamp_max: 50000, i_clamp_min: -50000 }
    joint3: { p: 5000, i: 50, d: 20, i_clamp_max: 50000, i_clamp_min: -50000 }
    joint4: { p: 500, i: 1, d: 0.05, i_clamp_max: 50000, i_clamp_min: -50000 }
    joint5: { p: 100, i: 1, d: 0.01, i_clamp_max: 50000, i_clamp_min: -50000 }

arm_group_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
  # gains:
  #   joint1:
  #     p: 100
  #     d: 1
  #     i: 1
  #     i_clamp: 1
  #   joint2:
  #     p: 100
  #     d: 1
  #     i: 1
  #     i_clamp: 1
  #   joint3:
  #     p: 100
  #     d: 1
  #     i: 1
  #     i_clamp: 1
  #   joint4:
  #     p: 100
  #     d: 1
  #     i: 1
  #     i_clamp: 1
  #   joint5:
  #     p: 100
  #     d: 1
  #     i: 1
  #     i_clamp: 1
