gazebo_ros_control:
  pid_gains:
    joint1: { p: 300.0, i: 10, d: 10.0, i_clamp: 10000.0 }
    joint2: { p: 1000.0, i: 20, d: 20.0, i_clamp: 10000.0 }
    joint3: { p: 1000.0, i: 20, d: 20.0, i_clamp: 10000.0 }
    joint4: { p: 100.0, i: 2, d: 1, i_clamp: 1000.0 }
    joint5: { p: 10.0, i: 0, d: 0.1, i_clamp: 1000.0 }
    joint6_fake: { p: 0.001, i: 0, d: 0.01, i_clamp: 1000.0 }

# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

arm_joint_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6_fake

# Position Controllers ---------------------------------------
# joint1_position_controller:
#   type: position_controllers/JointPositionController
#   joint: joint1
# joint2_position_controller:
#   type: position_controllers/JointPositionController
#   joint: joint2
# joint3_position_controller:
#   type: position_controllers/JointPositionController
#   joint: joint3
# joint4_position_controller:
#   type: position_controllers/JointPositionController
#   joint: joint4
# joint5_position_controller:
#   type: position_controllers/JointPositionController
#   joint: joint5
# joint6_position_controller:
#   type: position_controllers/JointPositionController
#   joint: joint6_fake
