# ros_control_boilerplate Settings -----------------------
# Settings for ros_control control loop

generic_hw_control_loop:
   loop_hz: 10
   cycle_time_error_threshold: 0.1

# Settings for ros_control hardware interface (used in generic_hw_interface.cpp)
hardware_interface:
   joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5

# Publish all joint states ----------------------------------
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
   type: joint_state_controller/JointStateController
   publish_rate: 5

# Joint Trajectory Controller -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
position_trajectory_controller:
   type: position_controllers/JointTrajectoryController
   # These joints can likely just be copied from the hardware_interface list above
   joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
